name: CI Api Production

on:
  push:
    branches:
      - master
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Git Pull and Build
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd ~/code/bot
            pm2 stop telegram_bot
            git pull origin master
            yarn
            pm2 start telegram_bot
